points:
  key:
    padding: cy
    tags: 
      1u: true
    footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
          choc:
            type: choc
            anchor:
              rotate: 180
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true

  zones:
    board:
      rotate: 5

      rows:
        bottom:
        home:
        top:
        toptop:

      columns:
        outouter:
          spread: cx
          row_overrides:
            bottom:
              tags:
                15u: true
                1u: false
              rotate: 90
              bind: [0,47.75,1,5]
        outer:
          stagger: -5
          spread: cx
          rows:
            bottom:
              bind: [0,1,0,0]
            home: 
              bind: [0,1,0,0]
            top:
              bind: [18.75,1,0,0]
            toptop.skip: true

        pinkie:
          stagger: 2
          spread: cx
          rows:
            bottom:
              bind: [0,2,2,0]
            home: 
              bind: [0,2.5,0,0]
            top:
              bind: [16.75,4,0,0]
            toptop.skip: true

        ring:
          stagger: 8
          spread: cx+1
          rotate: -2
          rows:
            bottom:
              bind: [0,3.5,9,0]
            home:  
              bind: [0,5,0,0]
            top: 
              bind: [8.5,6,0,0]
            toptop.skip: true

        middle:
          stagger: 8
          spread: cx+2.5
          rotate: -3
          rows:
            bottom:
              bind: [0,4,4,0]
            home:
              bind: [0,4,0,0]
            toptop.skip: true
            
          
        index:
          stagger: -4
          spread: cx+2
          rotate: -2
          rows:
            bottom:
              bind: [0,1,2,0]
            home:
              bind: [0,1,0,0]
            top: 
              bind: [3.5,1,0,5]
            toptop.skip: true
        inner:
          stagger: -2
          spread: cx
          rows:
            bottom:
              bind: [0,0,15.55,1]
            top: 
              bind: [5.5,0,0,0]
            toptop.skip: true


    thumb:
      anchor:
        ref: board_ring_bottom
        shift: [0,-25]

      rows:
        first:
        
      columns:
        ctrl: 
          stagger: 2.5
          rows: 
            first:
              tags:
                15u: true
                1u: false
              rotate: 90
              bind: [0,0,0,5]

        alt:
          stagger: 13
          rotate: -3
          spread: cx+1.55
          rows: 
            first:  
              bind: [0,3,3.7,2]

        shift:
          stagger: -4
          rotate: -2
          spread: cx+1.4

        e: 
          spread: cx
          stagger: -7
          rows: 
            first:
              tags:
                15u: true
                1u: false
              rotate: 90
              bind: [0,0,0,5]


outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx-0.5 , 1cx-0.5]
    polipouce:
      - type: polygon
        points: 
          - ref: thumb_ctrl_first
            shift: [-13.75,-5]
          - ref: thumb_e_first
            shift: [-13.6,-8.8]
          - ref: board_inner_bottom
            shift: [8,0]
          - ref: board_ring_bottom 

    cutouta:
      - type: outline
        name: raw
        fillet: 3
    cutoutb:
      - type: outline
        name: polipouce
        fillet: 3
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false
        tags: [1u]
    keycap_outlines15:
      - type: keys
        side: left
        size: [1.5cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false    
        tags: [15u]        
    preview:
        [keycap_outlines,keycap_outlines15]
    cutout: 
        [cutouta,cutoutb]

pcb: 
  